"use client";
import { useCallback, useEffect, useState } from "react";
import { motion } from "framer-motion";
import { BarChart3, BrainCircuit, Database, Lightbulb, RefreshCw, ShieldCheck, Sparkles, TrendingUp, TriangleAlert } from "lucide-react";
import { WorkspaceNavigation } from "@/components/navigation/workspace-navigation";
import { WorkspaceSidebar } from "@/components/navigation/workspace-sidebar";
import { WorkspaceTopbar } from "@/components/navigation/workspace-topbar";
import { getPersonalPatterns } from "@/lib/api";
import type { PersonalPatternsWorkspace } from "@/types/personal-patterns";

const card = "rounded-[2rem] border border-slate-200/80 bg-white shadow-xl shadow-slate-900/5 dark:border-white/10 dark:bg-[#11141f] dark:shadow-black/20";
const directionStyle = { positive: "border-emerald-200 bg-emerald-50/70 dark:border-emerald-500/15 dark:bg-emerald-500/[0.07]", warning: "border-amber-200 bg-amber-50/70 dark:border-amber-500/15 dark:bg-amber-500/[0.07]", neutral: "border-indigo-200 bg-indigo-50/70 dark:border-indigo-500/15 dark:bg-indigo-500/[0.07]" };

export function PersonalPatternsShell() {
  const [workspace, setWorkspace] = useState<PersonalPatternsWorkspace | null>(null);
  const [days, setDays] = useState(90);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setWorkspace(await getPersonalPatterns(days)); } catch (e) { setError(e instanceof Error ? e.message : "Could not analyze your personal patterns."); } finally { setLoading(false); } }, [days]);
  useEffect(() => { const id = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(id); }, [load]);

  return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-[#050711] dark:text-white">
    <WorkspaceSidebar insightTitle="Personal patterns" insightText="Discover repeatable relationships across your own productivity, focus, recovery, and wellbeing records." insightValue={workspace?.confidence ?? "Ready"} />
    <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="min-w-0 pb-28 xl:pl-[272px] xl:pb-0">
      <WorkspaceTopbar eyebrow="Explainable pattern discovery" title="Personal Patterns" description="Cross-module insights that show what appears to help or hinder your own workflow—without black-box claims." />
      <div className="mx-auto max-w-[1500px] space-y-6 px-4 py-6 sm:px-6 lg:px-8">
        <section className={`${card} relative overflow-hidden p-6 sm:p-8`}><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-cyan-500/15 blur-3xl" /><div className="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.18em] text-cyan-600 dark:text-cyan-300"><BrainCircuit className="h-4 w-4" />Connected intelligence</div><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">{workspace?.headline ?? "Finding your repeatable patterns"}</h1><p className="mt-4 text-sm leading-7 text-slate-600 dark:text-slate-300">{workspace?.summary ?? "Comparing your task, focus, sleep, energy, distraction, and time-tracking signals."}</p></div><div className="flex flex-wrap gap-2">{[30, 90, 180, 365].map((value) => <button key={value} onClick={() => setDays(value)} className={`rounded-xl px-4 py-2.5 text-sm font-black ${days === value ? "bg-slate-950 text-white dark:bg-white dark:text-slate-950" : "border border-slate-200 bg-white dark:border-white/10 dark:bg-white/[0.05]"}`}>{value} days</button>)}<button onClick={() => void load()} aria-label="Refresh personal patterns" className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-600 text-white"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /></button></div></div></section>
        {error ? <section className={`${card} border-rose-200 p-6 text-sm font-semibold text-rose-600 dark:border-rose-500/20 dark:text-rose-300`}>{error}</section> : null}
        {loading && !workspace ? <section className={`${card} grid min-h-[420px] place-items-center`}><RefreshCw className="h-8 w-8 animate-spin text-cyan-500" /></section> : null}
        {workspace ? <>
          <section className="grid gap-4 sm:grid-cols-3"><article className={`${card} p-6`}><Database className="h-5 w-5 text-indigo-500" /><p className="mt-4 text-4xl font-black">{workspace.records_analyzed}</p><p className="mt-1 text-xs font-bold text-slate-500">records analyzed</p></article><article className={`${card} p-6`}><Sparkles className="h-5 w-5 text-cyan-500" /><p className="mt-4 text-4xl font-black">{workspace.patterns.length}</p><p className="mt-1 text-xs font-bold text-slate-500">patterns found</p></article><article className={`${card} p-6`}><ShieldCheck className="h-5 w-5 text-emerald-500" /><p className="mt-4 text-3xl font-black">{workspace.confidence}</p><p className="mt-1 text-xs font-bold text-slate-500">overall confidence</p></article></section>
          {workspace.patterns.length ? <section className="grid gap-5 xl:grid-cols-2">{workspace.patterns.map((pattern) => <article key={pattern.id} className={`${card} p-6 sm:p-7`}><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-slate-500 dark:bg-white/[0.06] dark:text-slate-300">{pattern.category}</span><h2 className="mt-4 text-xl font-black">{pattern.title}</h2></div><span className="rounded-full border border-slate-200 px-3 py-1 text-[10px] font-black uppercase tracking-wider dark:border-white/10">{pattern.confidence}</span></div><div className={`mt-5 rounded-2xl border p-5 ${directionStyle[pattern.direction]}`}><div className="flex gap-3"><TrendingUp className="mt-0.5 h-5 w-5 shrink-0" /><p className="font-black leading-7">{pattern.insight}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{pattern.explanation}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{pattern.evidence.map((item) => <div key={item.label} className="rounded-2xl bg-slate-50 p-4 dark:bg-white/[0.035]"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{item.label}</p><p className="mt-2 text-lg font-black">{item.value}</p></div>)}</div><div className="mt-5 flex gap-3 rounded-2xl bg-violet-500/[0.07] p-4"><Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-violet-500" /><div><p className="text-xs font-black uppercase tracking-wider text-violet-600 dark:text-violet-300">Try next</p><p className="mt-1 text-sm font-semibold leading-6">{pattern.action}</p></div></div><p className="mt-4 text-[10px] font-bold uppercase tracking-wider text-slate-400">Sample: {pattern.sample_size} records</p></article>)}</section> : <section className={`${card} grid min-h-[280px] place-items-center p-8 text-center`}><div><BarChart3 className="mx-auto h-10 w-10 text-slate-300" /><h2 className="mt-4 text-2xl font-black">Your baseline is still forming</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">Keep using FlowMind across several modules. Patterns only appear when enough comparable records exist.</p></div></section>}
          {workspace.data_gaps.length ? <section className={`${card} p-6 sm:p-8`}><div className="flex items-center gap-3"><TriangleAlert className="h-5 w-5 text-amber-500" /><h2 className="text-xl font-black">Improve future pattern confidence</h2></div><div className="mt-5 grid gap-3 md:grid-cols-2">{workspace.data_gaps.map((gap) => <div key={gap} className="rounded-2xl border border-amber-200 bg-amber-50/70 p-4 text-sm font-semibold leading-6 dark:border-amber-500/15 dark:bg-amber-500/[0.07]">{gap}</div>)}</div></section> : null}
          <p className="px-2 text-center text-xs leading-5 text-slate-400">{workspace.disclaimer}</p>
        </> : null}
      </div>
    </motion.main><WorkspaceNavigation variant="mobile" />
  </div>;
}
